enableRobotsTXT = true
disableKinds = ["taxonomy", "term", "RSS"]
disableHugoGeneratorInject = true

[permalinks.page]
blog = "/blog/:year/:month/:day/:filename"

[markup.goldmark.renderer]
xhtml = true
unsafe = true

[mediaTypes."application/atom+xml"]
suffixes = ["xml"]

[outputFormats.atom]
basename = "atom"
isPlainText = true
mediaType = "application/xml"
path = "../"

[outputs]
home = ['html']
section = ['html', 'atom']

[markup.highlight]
noClasses = false
